// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input D:/Reza/qmk_firmware/keyboards/0_0/chain/graphics/win.gif --output D:/Reza/qmk_firmware/keyboards/0_0/chain/graphics --format pal16 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_win_length;
extern const uint8_t  gfx_win[400963];
